export type LegalSection = {
  title: string;
  paragraphs?: string[];
  list?: string[];
  subsections?: LegalSection[];
};

export type LegalDocumentData = {
  heroTitle: string;
  heroDescription: string;
  documentTitle: string;
  companyLine: string;
  lastUpdated: string;
  pdfPath: string;
  sections: LegalSection[];
};

export const legalEmail = "hello@plisticmedia.com";

export const termsDocument: LegalDocumentData = {
  heroTitle: "Terms and conditions",
  heroDescription: "Plistic's current terms and conditions of service.",
  documentTitle: "Terms and Conditions of Service",
  companyLine: "A trading name of Songplistic Ltd, a company registered in Scotland",
  lastUpdated: "3 July 2026 (Version 8)",
  pdfPath: "/assets/legal/plistic-terms-and-conditions-v5.pdf",
  sections: [
    {
      title: "1. Who We Are",
      paragraphs: [
        "These Terms and Conditions (\"Terms\") govern all work undertaken by Plistic, the trading name of Songplistic Ltd (\"we\", \"us\", \"our\", or \"Plistic\"), a company registered in Scotland under company number SC699049, with its registered office at 2 West Drive Cottage, Stracathro, Brechin, Scotland, DD9 7QF.",
        "These Terms apply to every project, booking, and engagement between Plistic and any client (\"you\", \"your\", or \"the Client\"), whether confirmed through our website, by email, verbally, or by any other means. By confirming a booking, paying a deposit, or instructing us to begin work, you agree to be bound by these Terms.",
        "These Terms are governed by the law of Scotland, and any dispute arising from them is subject to the exclusive jurisdiction of the Scottish courts.",
      ],
    },
    {
      title: "2. Our Services",
      paragraphs: [
        "Plistic provides media production and related services, including but not limited to: podcast production (full service and post-production only), video production, documentary production, event filming, music video production, advertising production and campaign management, content research and strategy, project management for media production, presenting and performance coaching, podcast SEO, multi-platform distribution, and analytics reporting.",
        "The specific scope of services for any individual project is confirmed in writing before work begins, in the form of a Project Confirmation (see Section 3.4). Any service, deliverable, or feature not explicitly included in the Project Confirmation is not included in the agreed price and may be chargeable as additional work.",
      ],
    },
    {
      title: "3. How a Project is Booked",
      subsections: [
        {
          title: "3.1 Quote and Call Route",
          paragraphs: [
            "Most podcast, video production, and event filming enquiries begin with an estimate generated through our website quote tool, followed by a free discovery call to confirm scope, requirements, and final pricing. No payment or card details are required to book this call.",
          ],
        },
        {
          title: "3.2 Bespoke Enquiry Route",
          paragraphs: [
            "For projects that do not suit a fixed calculator - including documentaries and other bespoke commissions - you can leave your details and some initial information about your project through our website, and book a call directly into our calendar without needing to speak to anyone first. This route does not require a prior brief review or any gatekeeping step - the call itself is where scope is established.",
          ],
        },
        {
          title: "3.3 Self-Serve Route",
          paragraphs: [
            "For simple, clearly defined jobs (such as post-production work submitted through our upload portal) and for coaching sessions, which are offered at a fixed rate, you may be able to confirm and pay for a booking without a prior call.",
          ],
        },
        {
          title: "3.4 Project Confirmation",
          paragraphs: [
            "Regardless of route, a project is only confirmed once you have received a written Project Confirmation from us, setting out the agreed scope, price, timeline, and any specific terms for that project, and the applicable deposit (see Section 5) has been paid. We reserve the right to decline any project before this point, including after a discovery call has taken place.",
            "A quote generated by our online estimator is an indicative range only and does not constitute a binding offer. The final price is confirmed in the Project Confirmation.",
          ],
        },
      ],
    },
    {
      title: "4. Project Briefs and Client Responsibilities",
      paragraphs: ["To deliver your project on time and to the standard you expect, we rely on you to:"],
      list: [
        "Complete any project brief or questionnaire we provide, accurately and within a reasonable timeframe.",
        "Provide any assets, footage, audio, or materials required for production in the formats and by the deadlines we specify.",
        "Respond to requests for feedback, approval, or clarification within the timeframes set out in your Project Confirmation.",
        "Connect us with any contacts relevant to the project - such as guests, contributors, or colleagues within your organisation - that we reasonably need in order to complete the work.",
        "Make appropriate time and space available to engage with the production process, including responding to scheduling requests and attending agreed sessions.",
        "Ensure you have the right to use any third-party material (music, footage, images, branding, or otherwise) that you ask us to incorporate into your project.",
      ],
      subsections: [
        {
          title: "",
          paragraphs: [
            "If delays on your part affect our ability to deliver on the agreed timeline, the delivery date will be adjusted accordingly, and we reserve the right to charge for any additional costs reasonably incurred as a result (including rescheduled studio time, crew, or third-party costs).",
          ],
        },
      ],
    },
    {
      title: "5. Payment Terms",
      subsections: [
        {
          title: "5.1 Deposit and Final Payment",
          paragraphs: [
            "Unless otherwise agreed in writing, payment for full-service production projects is structured as follows:",
          ],
          list: [
            "50% of the total project value is payable as a deposit before production work begins.",
            "The remaining 50% is payable on delivery of the final agreed deliverables, before final files are released for your unrestricted use.",
          ],
        },
        {
          title: "5.2 Self-Serve, Portal, and Coaching Bookings",
          paragraphs: [
            "For projects booked and paid through our self-serve upload portal, and for coaching sessions, full payment is taken at the point of booking, before work begins.",
          ],
        },
        {
          title: "5.3 Invoicing and Payment Deadlines",
          paragraphs: [
            "Following a discovery call, we issue a deposit invoice by email with a payment link. The quoted price is valid for 7 days from the date of the Project Confirmation. If the deposit is not received within this window, we reserve the right to requote before accepting the booking.",
            "Final invoices are issued on completion of the agreed deliverables and are payable within 7 days of the invoice date, unless otherwise agreed in writing.",
          ],
        },
        {
          title: "5.4 Late Payment",
          paragraphs: [
            "If an invoice is not paid by its due date, we are entitled to charge statutory interest under the Late Payment of Commercial Debts (Interest) Act 1998, which applies in full in Scotland. The rate is 8% per annum above the Bank of England base rate in force on the date payment became overdue, calculated daily on the outstanding amount from the due date until paid.",
            "In addition to interest, we are entitled to a fixed compensation sum under the Late Payment of Commercial Debts (Scotland) Regulations 2002, as follows:",
          ],
          list: [
            "\u00a340 for a debt of less than \u00a31,000.",
            "\u00a370 for a debt of \u00a31,000 or more but less than \u00a310,000.",
            "\u00a3100 for a debt of \u00a310,000 or more.",
          ],
          subsections: [
            {
              title: "",
              paragraphs: [
                "These charges apply automatically by law to qualifying business-to-business debts and do not need to be separately agreed in this contract, but we set them out here for clarity. We reserve the right to suspend work on any project where payment is overdue.",
              ],
            },
          ],
        },
        {
          title: "5.5 VAT",
          paragraphs: [
            "Plistic (Songplistic Ltd) is not currently registered for VAT. All prices quoted are therefore the total amount payable, with no VAT added. If this changes, we will update our pricing and these Terms accordingly and notify clients in advance.",
          ],
        },
      ],
    },
    {
      title: "6. Referral Programme",
      paragraphs: [
        "If you refer a new client to Plistic - someone who has not worked with us before - and that referral results in a confirmed, paid project, we will pay you a referral fee on the following basis:",
      ],
      list: [
        "The referral fee is 10% of the total value of the referred client's first project with Plistic.",
        "It applies only to a new client's first project with us. It is a thank you for the introduction, not an ongoing share of any future work that client books with us.",
        "The fee is paid once the client's final invoice for that first project has been settled in full.",
        "To be eligible, the referral must be submitted through our official referral form on our website before the prospective client first contacts us by any other means - directly, through a discovery call, through our quote tool, or otherwise.",
        "We do not pay referral fees based on a claim made after a project has already been agreed or signed. If we have no record of a referral submitted through our official form before the client first made contact, no referral fee is payable, regardless of any conversation that may have taken place outside our systems.",
        "Simply mentioning Plistic to someone in conversation, without submitting the referral through our form, does not qualify for a referral fee.",
      ],
      subsections: [
        {
          title: "",
          paragraphs: [
            "We reserve the right to decline a referral fee, or to request further information, where it is unclear whether a genuine introduction has taken place, or where the prospective client was already known to us.",
            "This referral programme may be amended or withdrawn at any time. The terms in effect at the time a referral is submitted will apply to that referral.",
          ],
        },
      ],
    },
    {
      title: "7. Cancellations, Rescheduling, and Changes",
      subsections: [
        {
          title: "7.1 Cancellation of the Whole Project by the Client",
          paragraphs: [
            "Once a deposit has been paid and production work has begun on your project, the deposit becomes non-refundable. This reflects the time, resources, and third-party costs (such as studio bookings, crew, or freelancer fees) that are committed on your behalf once production starts, and is calculated as a genuine pre-estimate of the loss we would otherwise incur - not as a penalty for cancelling.",
            "If you cancel before production work has begun, your deposit will be refunded in full, less any costs we have already reasonably and necessarily incurred on your behalf at that point (such as third-party bookings made specifically for your project).",
            "If a project is cancelled after more than 50% of the agreed work has been completed (assessed by reference to time spent, resources used, and deliverables produced relative to the total scope), we reserve the right to charge an additional fee reflecting the proportion of work completed beyond the deposit amount, up to the full project value. We will set out the basis for any such charge in writing, showing the work completed, before invoicing.",
          ],
        },
        {
          title: "7.2 Rescheduling or Cancelling a Specific Filming or Recording Day",
          paragraphs: [
            "Where your project involves one or more specific filming, recording, or event days that have been confirmed in your Project Confirmation, the following applies in addition to Section 7.1:",
          ],
          list: [
            "If you need to reschedule or cancel a confirmed filming or recording day with at least 5 working days' notice, we will work with you to find a new date at no additional charge.",
            "If you reschedule or cancel a confirmed filming or recording day with less than 5 working days' notice, we reserve the right to charge the full agreed rate for that filming day, as the session will have been reserved in our schedule and we are unlikely to be able to reallocate the time or crew at short notice. Any third-party costs already committed on your behalf (such as venue hire) will also be chargeable. We will confirm any such charge in writing.",
          ],
        },
        {
          title: "7.3 Cancellation or Postponement by Plistic",
          paragraphs: [
            "In the unlikely event that we need to cancel or postpone a confirmed project (for reasons including but not limited to illness, equipment failure, or circumstances beyond our reasonable control), we will notify you as soon as possible and either reschedule at no additional cost or refund any payments made for work not yet delivered.",
          ],
        },
        {
          title: "7.4 Changes to Scope",
          paragraphs: [
            "If you wish to change the scope of a project after the Project Confirmation has been issued (for example, adding episodes, extending runtime, or requesting additional deliverables), we will provide a revised quote for the additional work. Changes in scope may affect the delivery timeline.",
          ],
        },
      ],
    },
    {
      title: "8. Revisions and Feedback",
      paragraphs: [
        "Unless otherwise stated in your Project Confirmation, the price for full-service production projects includes up to two rounds of revisions on delivered work.",
        "To help us turn revisions around quickly and accurately, please make feedback as specific as possible - referencing exact timestamps and clear instructions (for example, \"at 2 minutes 14 seconds, please trim this section\") rather than general impressions. This is set out in full in the onboarding pack provided at the start of your project.",
        "Any request for revisions beyond the included rounds, or any request that amounts to a substantial change in direction rather than a refinement of agreed work, is treated as additional work and will be charged at the relevant rate from our current pricing sheet for that type of work, confirmed with you in writing before that work begins.",
        "Revision requests should be submitted within 5 working days of delivery unless a different timeframe is agreed in your Project Confirmation. If we do not receive feedback within 10 working days of delivery, and have made reasonable attempts to contact you during that time, we will treat the project as approved and proceed to final invoicing on that basis.",
      ],
    },
    {
      title: "9. Recording and Filming Time",
      paragraphs: [
        "Your Project Confirmation sets out the time allocated for any recording, filming, or event coverage session - for example, a half-day, full-day, or a specific number of hours for a podcast recording.",
        "If a session runs beyond the allocated time, additional time is charged at 1.5 times the pro-rata rate for that booking (calculated from the agreed session rate set out in your Project Confirmation). This reflects the genuine cost to us of a session overrunning - including the knock-on effect on other bookings, travel, and crew time - and is standard practice in the production industry. Where practical, we will let you know during the session if it looks likely to run over, so you can decide whether to continue or stop at the agreed time.",
        "This applies whether the overrun is due to the format of the session (for example, a podcast recording that runs significantly longer than the planned episode length) or the length of an event running beyond its scheduled finish time. Overage charges will be confirmed and invoiced alongside the final invoice for the project.",
      ],
    },
    {
      title: "10. Turnaround Times",
      paragraphs: [
        "Estimated turnaround times are confirmed in your Project Confirmation. Turnaround begins from the point we have received all necessary assets, briefs, and information from you - not from the date the project was booked.",
        "Where a project is booked through our self-serve portal, turnaround tiers and their associated timeframes are clearly stated at the point of booking.",
        "We will make reasonable efforts to meet all agreed deadlines. If we expect to miss an agreed deadline for reasons within our control, we will tell you as early as possible, before the deadline passes, and agree a new date with you directly.",
      ],
    },
    {
      title: "11. Ownership and Usage",
      subsections: [
        {
          title: "11.1 Ownership of Final Deliverables",
          paragraphs: [
            "On payment in full, ownership of the final agreed deliverables (the specific files set out in your Project Confirmation) transfers to you. You own these outright - we are not licensing them to you - and you are free to use, reproduce, and distribute them for the purposes agreed at the outset of your project, without further payment to us.",
          ],
        },
        {
          title: "11.2 What Plistic Retains",
          paragraphs: [
            "Unless raw footage delivery has been specifically agreed and paid for as part of your project, raw footage, unedited audio, project files, working materials, and any alternative cuts or versions not delivered as final deliverables remain the property of Plistic.",
            "We also retain a permanent, royalty-free licence to use the final deliverables (or excerpts, stills, and behind-the-scenes content from the production of those deliverables) in our own portfolio, website, case studies, social media, and other promotional materials, unless you tell us in writing before or at the start of your project that you would prefer otherwise, or that you would like us to seek your approval before each use. We will record and respect that preference.",
          ],
        },
        {
          title: "11.3 Third-Party Material",
          paragraphs: [
            "You are responsible for ensuring you hold the necessary rights, licences, or permissions for any third-party material (music, archive footage, branding, images, or otherwise) that you provide to us or specifically direct us to use. We will use reasonable care in sourcing any licensed material on your behalf, but we are not liable for any third-party intellectual property claim arising from material you have supplied or specifically directed us to use.",
          ],
        },
      ],
    },
    {
      title: "12. Confidentiality",
      paragraphs: [
        "We treat all client information, briefs, business plans, and unreleased content as confidential, and will not disclose this information to third parties without your consent, except where required by law.",
        "If your project requires a specific non-disclosure agreement beyond the confidentiality commitment in these Terms, please let us know before work begins so that an appropriate agreement can be put in place.",
      ],
    },
    {
      title: "13. Liability",
      paragraphs: [
        "We will perform our services with reasonable skill and care, in line with standard practice for media production services in Scotland.",
        "We are not liable for any indirect, consequential, or special loss, including loss of profit, loss of business, or loss of opportunity, arising from our work, except where such liability cannot be excluded by law.",
        "Our total liability for any claim arising from a project, whether in contract, negligence, or otherwise, is limited to the total fees paid by you for that specific project.",
        "Nothing in these Terms excludes or limits our liability for death or personal injury caused by our negligence, or for any other liability that cannot be excluded or limited under Scots law.",
      ],
    },
    {
      title: "14. Insurance",
      paragraphs: [
        "Plistic holds professional indemnity insurance appropriate to the scale and nature of our work. Details are available on request.",
      ],
    },
    {
      title: "15. Force Majeure",
      paragraphs: [
        "Neither party is liable for any failure or delay in performing their obligations under these Terms where that failure or delay results from circumstances beyond their reasonable control, including but not limited to acts of God, fire, flood, extreme weather, strikes, pandemic, government restriction, or failure of third-party suppliers.",
      ],
    },
    {
      title: "16. General",
      subsections: [
        {
          title: "16.1 Entire Agreement",
          paragraphs: [
            "These Terms, together with the relevant Project Confirmation, constitute the entire agreement between Plistic and the Client for that project, and supersede any prior discussions, representations, or agreements relating to that project.",
          ],
        },
        {
          title: "16.2 Variation",
          paragraphs: [
            "These Terms may be updated from time to time. Each version is dated at the top of this document (see \"Last updated\" above). The version in effect on the date a Project Confirmation is issued applies to that project for its duration, even if these Terms are subsequently updated.",
          ],
        },
        {
          title: "16.3 Severability",
          paragraphs: [
            "If any provision of these Terms is found to be unenforceable or invalid, that provision will be limited or eliminated to the minimum extent necessary, and the remaining provisions will continue in full force.",
          ],
        },
        {
          title: "16.4 No Waiver",
          paragraphs: [
            "A failure by either party to enforce any provision of these Terms at any time does not constitute a waiver of that provision.",
          ],
        },
        {
          title: "16.5 Governing Law",
          paragraphs: [
            "These Terms are governed by and construed in accordance with the law of Scotland, and the parties submit to the exclusive jurisdiction of the Scottish courts.",
          ],
        },
      ],
    },
    {
      title: "17. Partner Directory",
      paragraphs: [
        "This section governs the Plistic partner directory (the \"Directory\"), which is separate from the production services described above and was added when the Directory launched.",
      ],
      subsections: [
        {
          title: "17.1 An introduction service",
          paragraphs: [
            "The Directory lists independent creative and media providers (\"Sellers\" or \"Partners\") so potential buyers can find and contact them. Where a buyer contacts a Seller through the Directory - for example by sending an enquiry - and then arranges work with them directly, Plistic is only making an introduction. In that case Plistic is not a party to any contract, agreement, or transaction between the buyer and the Seller, takes no commission on it, and is not responsible for the work, conduct, pricing, deliverables, or any act or omission of any Seller or buyer. Any agreement you enter into that way is solely between you and that other party.",
            "Separately, some Sellers offer packages that can be booked and paid for through the platform (\"Marketplace Bookings\"). Marketplace Bookings are governed by Section 18. For those, Plistic facilitates payment and charges a commission, but Plistic still does not itself carry out the Seller's work and is not the supplier of the services.",
          ],
        },
        {
          title: "17.2 Listings and pricing",
          paragraphs: [
            "Prices and packages shown on a listing are indicative, provided by the Seller for information only. They are not offers capable of acceptance and do not create a contract. Buyers should confirm all scope, pricing, and terms directly with the Seller.",
          ],
        },
        {
          title: "17.3 Seller accounts and responsibilities",
          paragraphs: [
            "By creating a Seller account you agree that: the information in your profile and listings is accurate and not misleading; you own or are licensed to use all content you upload and it does not infringe anyone's rights; you will respond to buyer enquiries honestly, lawfully, and in good faith; you will not post unlawful, offensive, or fraudulent content; and that Plistic may review, edit, pause, or remove any listing, and suspend any account, at its discretion to keep the Directory accurate and trustworthy.",
          ],
        },
        {
          title: "17.4 Trusted Partner and featured status",
          paragraphs: [
            "Plistic may highlight selected listings as \"Trusted Partner\" or featured entries. Featured placement may be offered free at Plistic's discretion or as a paid subscription. Featured status is editorial promotion within the Directory only and does not mean Plistic endorses, guarantees, or is responsible for that Seller's work.",
          ],
        },
        {
          title: "17.5 Enquiries",
          paragraphs: [
            "When a buyer submits an enquiry on a listing, their name, email, and message are shared with the relevant Seller (and with Plistic) so the Seller can respond directly. See our Privacy Policy for how this data is handled.",
          ],
        },
        {
          title: "17.6 Liability",
          paragraphs: [
            "To the fullest extent permitted by law, and subject to Section 13, Plistic is not liable for any loss arising from your dealings with a Seller or buyer, from reliance on listing content, or from use of the Directory.",
          ],
        },
      ],
    },
    {
      title: "18. Marketplace Bookings and Payments",
      paragraphs: [
        "This section applies where a Seller has enabled online booking on one or more of their packages and a buyer books and pays for that package through the Plistic platform (a \"Marketplace Booking\"). It is in addition to Section 17.",
      ],
      subsections: [
        {
          title: "18.1 The contract is between buyer and Seller",
          paragraphs: [
            "A Marketplace Booking is a contract for the Seller's services between the buyer and the Seller. Plistic is not the supplier of those services and is not a party to that contract. The Seller alone is responsible for carrying out the work, for its quality, scope, timing, and for any warranties, and for dealing with the buyer in good faith. Plistic's role is limited to operating the Directory and facilitating the payment described below.",
          ],
        },
        {
          title: "18.2 Payment and escrow",
          paragraphs: [
            "Payment for a Marketplace Booking is taken from the buyer at the point of booking, through our payment provider, Stripe. The payment is then held securely (in escrow) and is not paid out to the Seller straight away. It is released to the Seller once the booking is completed as described in Section 18.5. Plistic does not see or store buyers' card details; these are handled by Stripe.",
          ],
        },
        {
          title: "18.3 Commission",
          paragraphs: [
            "Plistic charges the Seller a commission on each Marketplace Booking for operating the platform and facilitating payment. The commission is currently 10% of the booking value, reduced to 5% for Sellers with an active featured membership. The commission rate that applies to a booking is the rate in effect at the time the booking is made, and is deducted from the amount paid out to the Seller. Plistic may change its commission rates from time to time; any change applies only to bookings made after the change.",
          ],
        },
        {
          title: "18.4 Seller payouts",
          paragraphs: [
            "To receive Marketplace Booking payments, a Seller must set up a connected payout account through Stripe and complete Stripe's identity and verification requirements. Payouts are made by Stripe to the Seller's connected account, less Plistic's commission and any applicable payment-processing fees. Plistic does not hold Sellers' bank details. Sellers are responsible for their own tax affairs, including any VAT, on the income they receive.",
          ],
        },
        {
          title: "18.5 Delivery, confirmation, and release of funds",
          paragraphs: [
            "When the Seller has completed the work, they mark the booking as delivered. The buyer is then asked to confirm they are satisfied, which releases the held funds to the Seller. If the buyer neither confirms nor raises an issue (see Section 18.7) within 14 days of the booking being marked delivered, the funds are automatically released to the Seller. Confirming, or allowing automatic release, does not remove any legal rights the buyer may have against the Seller.",
          ],
        },
        {
          title: "18.6 Cancellations and refunds",
          paragraphs: [
            "Before funds are released, a buyer who has a problem with a booking may raise an issue and request a refund (see Section 18.7). Where Plistic still holds the payment, Plistic can refund the buyer in full or release the funds to the Seller. Once funds have been released to the Seller (including by automatic release), any refund, redo, or further remedy is a matter between the buyer and the Seller under their contract; Plistic is not obliged to refund amounts it no longer holds.",
          ],
        },
        {
          title: "18.7 Disputes",
          paragraphs: [
            "If a buyer is not satisfied, they may raise a dispute through their account before the funds are released. Raising a dispute pauses the automatic release. Plistic will look at the information provided by both sides and decide, acting reasonably, whether to refund the buyer or release the funds to the Seller. This decision relates only to the payment Plistic is holding; it is not a legal determination of the underlying contract between buyer and Seller, and it does not affect either party's right to pursue the other separately. Both buyers and Sellers agree to engage with this process honestly and in good faith.",
          ],
        },
        {
          title: "18.8 Reviews",
          paragraphs: [
            "Only a buyer who has completed a Marketplace Booking with a Seller may leave a review of that Seller through the platform. Reviews must be honest, based on genuine experience, and must not be unlawful, defamatory, or abusive. Plistic may remove reviews that breach these Terms. Reviews are shown for up to 12 months and then expire, so that a Seller's rating reflects recent work.",
          ],
        },
        {
          title: "18.9 Seller obligations for Marketplace Bookings",
          paragraphs: [
            "In addition to Section 17.3, a Seller offering Marketplace Bookings agrees that their package descriptions, prices, and delivery times are accurate and not misleading; that they will deliver the work as described and within the stated timeframe; that they are legally able to supply the services and will comply with all applicable law; and that they, not Plistic, are the supplier of the services to the buyer.",
          ],
        },
        {
          title: "18.10 Plistic's liability for Marketplace Bookings",
          paragraphs: [
            "Subject to Section 13, Plistic's responsibility in relation to a Marketplace Booking is limited to operating the platform and handling the payment as described in this Section 18. Plistic is not liable for the Seller's work or conduct, for a Seller's failure to deliver, or for any loss arising from the contract between a buyer and a Seller. Where Plistic holds funds pending release, it does so as a payment facilitator and not as a trustee, bank, or insurer.",
          ],
        },
      ],
    },
    {
      title: "19. Contact",
      paragraphs: [
        `If you have any questions about these Terms, please contact us at ${legalEmail}.`,
        "Plistic is the trading name of Songplistic Ltd, a company registered in Scotland under company number SC699049. Registered office: 2 West Drive Cottage, Stracathro, Brechin, Scotland, DD9 7QF.",
      ],
    },
  ],
};

export const privacyDocument: LegalDocumentData = {
  heroTitle: "Privacy policy",
  heroDescription: "How Plistic collects, uses, and protects personal data.",
  documentTitle: "Privacy Policy",
  companyLine: "A trading name of Songplistic Ltd, a company registered in Scotland",
  lastUpdated: "3rd July 2026",
  pdfPath: "/assets/legal/plistic-privacy-policy-v3.pdf",
  sections: [
    {
      title: "1. Who We Are",
      paragraphs: [
        "This Privacy Policy explains how Plistic, the trading name of Songplistic Ltd (\"we\", \"us\", \"our\"), a company registered in Scotland under company number SC699049 with its registered office at 2 West Drive Cottage, Stracathro, Brechin, Scotland, DD9 7QF, collects, uses, and protects your personal data when you visit our website or get in touch with us.",
        `We are the data controller for the personal data described in this policy. If you have any questions, you can contact us at ${legalEmail}.`,
      ],
    },
    {
      title: "2. What Information We Collect",
      paragraphs: ["We only collect personal data that you choose to give us, through the following channels:"],
      subsections: [
        {
          title: "2.1 Contact and Enquiry Forms",
          paragraphs: [
            "If you fill in a contact form, brief form, or enquiry form on our website, we collect whatever information you provide - typically your name, email address, and details about your project. Phone number is collected if you choose to provide it.",
          ],
        },
        {
          title: "2.2 Quote Calculator",
          paragraphs: [
            "If you use our quote estimator, we collect the selections you make (service type, scope, budget range, and similar) in order to generate an indicative price range. If you choose to proceed and leave your contact details, we collect those in the same way as Section 2.1.",
          ],
        },
        {
          title: "2.3 Booking a Call",
          paragraphs: [
            "Our discovery calls are booked through Calendly. When you book a call, Calendly collects your name, email address, and any information you provide in the booking form on our behalf. Calendly processes this data as a processor acting on our instructions - see Section 6 for more on third parties we work with.",
          ],
        },
        {
          title: "2.4 Referral and Partnership Forms",
          paragraphs: [
            "If you submit a referral or a partnership enquiry, we collect your name and email address, along with the name and contact details of anyone you refer to us (with your confirmation that you are entitled to share this).",
          ],
        },
        {
          title: "2.5 Email and Other Direct Correspondence",
          paragraphs: [
            "If you email us, call us, or speak with us directly, we collect and retain that correspondence and any personal data included in it, in order to respond and manage our relationship with you. This includes contacts we hold in our CRM - every person in our CRM is someone we have had a genuine prior conversation or working relationship with, such as a past client, event contact, or business connection.",
          ],
        },
        {
          title: "2.6 Website Analytics",
          paragraphs: [
            "We use a privacy-first, cookieless analytics tool (Vercel Web Analytics) to understand how visitors use our website - for example, which pages are viewed, how people arrive, and which actions are taken (such as sending an enquiry or signing up). This data is aggregated, does not use tracking cookies, and does not identify you personally.",
          ],
        },
        {
          title: "2.7 Cookies",
          paragraphs: [
            "Our website uses only strictly necessary cookies - those required for the site to function, such as keeping you signed in to your account and remembering site access during our pre-launch period. We do not use advertising or third-party tracking cookies, which is why you will not see a cookie consent banner. If we ever introduce non-essential cookies, we will ask for your consent first.",
          ],
        },
        {
          title: "2.8 Partner Directory",
          paragraphs: [
            "If you create a Seller account in our partner directory, we collect the email address you sign in with and the profile and listing details you choose to publish (including any images or media you upload). If you submit an enquiry on a Seller's listing, we collect your name, email, and message - and share these with the relevant Seller so they can reply to you directly (see Sections 6 and 7).",
            "If you book and pay for a Seller's package through the platform (a Marketplace Booking), we collect the information needed to process that payment and manage your order - such as your email address, the order details, and payment confirmation information. Card payments are handled by our payment provider, Stripe; we do not see or store your full card details. We share the order details with the relevant Seller so they can carry out the work, and Sellers who receive payouts provide their own details directly to Stripe.",
          ],
        },
      ],
    },
    {
      title: "3. How We Use Your Information",
      paragraphs: ["We use the personal data described above for the following purposes:"],
      list: [
        "To respond to your enquiry and provide you with a quote or information about our services.",
        "To manage bookings and discovery calls.",
        "To deliver a project you have commissioned, including all communication, scheduling, and administration involved.",
        "To process referrals and partnership enquiries.",
        "To stay in touch with past clients and contacts we have a genuine working relationship with, including by email through our CRM (currently managed via Mailchimp).",
        "To understand how people use our website, so we can improve it.",
        "To meet our own legal, accounting, and tax obligations.",
      ],
      subsections: [
        {
          title: "",
          paragraphs: ["We do not use your personal data for automated decision-making or profiling."],
        },
      ],
    },
    {
      title: "4. Our Legal Basis for Processing",
      paragraphs: ["We rely on the following lawful bases under UK GDPR, depending on the situation:"],
      list: [
        "Contract - where we need your information to provide a service you have asked for or agreed to pay for.",
        "Legitimate interests - where we need your information to respond to an enquiry, manage our business relationship with you, stay in touch with existing contacts, or improve our services, and this does not unfairly affect your rights.",
        "Legal obligation - where we are required to keep certain records, such as for tax and accounting purposes.",
      ],
    },
    {
      title: "5. Payments and Invoicing",
      paragraphs: [
        "For our own production projects, we issue invoices directly by email once a project is confirmed, and payment is arranged separately between you and us. Details of how to pay are provided on the invoice itself.",
        "For directory Marketplace Bookings - where you book and pay for a Seller's package through the platform - payment is taken through our payment provider, Stripe. Stripe processes your card payment and (for Sellers) makes payouts; it acts as an independent payment processor. We do not see or store your full card details. See Section 6 for more on Stripe as a third party.",
      ],
    },
    {
      title: "6. Who We Share Your Information With",
      paragraphs: [
        "Your personal data is accessed by people working within Plistic who need it to do their job - for example to respond to your enquiry or deliver your project. We do not sell or rent your personal data to anyone. We share personal data only with the following organisations, where necessary to run our business:",
      ],
      list: [
        "Calendly - to manage bookings for discovery calls.",
        "Google - for website analytics (Google Analytics).",
        "Mailchimp - to manage our CRM and send email communications to existing contacts.",
        "Supabase - the database, sign-in, and file storage that power the partner directory and our website forms.",
        "Resend - to send transactional emails such as enquiry notifications, confirmations, and sign-in links.",
        "Stripe - to process marketplace payments securely and make payouts to Sellers. Where you make a booking, Stripe receives the payment information needed to take and process that payment.",
        "Vercel - website and application hosting.",
        "Our accountant - for invoicing, tax, and financial record-keeping.",
        "Any freelancer or third party we bring onto a specific project (for example, a guest researcher or specialist) - only where relevant to delivering that project, and only the information they need.",
        "Directory Sellers - when you submit an enquiry on a listing, your enquiry details are shared with that Seller so they can respond to you.",
      ],
      subsections: [
        {
          title: "",
          paragraphs: [
            "Several of these providers (including Calendly, Google, Mailchimp, Resend, Stripe, and Vercel) are based in or transfer data to the United States, so using them involves transferring some personal data outside the UK. Each safeguards this under recognised UK data protection mechanisms - primarily the UK Extension to the EU-US Data Privacy Framework, backed up by Standard Contractual Clauses with the UK Addendum. These are the standard, legally recognised ways of protecting personal data when it is transferred to the US, and they are the same mechanisms used by the vast majority of UK businesses using these or similar tools.",
          ],
        },
      ],
    },
    {
      title: "7. How Long We Keep Your Information",
      paragraphs: ["We keep personal data only for as long as necessary for the purpose it was collected:"],
      list: [
        "Enquiries that do not become a project: retained for up to 12 months, then deleted, unless you ask us to delete it sooner.",
        "Client and project information: retained for the duration of our working relationship and for 6 years afterwards, in line with our legal obligations for tax and accounting records.",
        "CRM contacts: retained for as long as we have an active business relationship or reasonable basis to stay in touch, and removed on request at any time.",
        "Referral and partnership enquiries: retained for as long as relevant to the referral or partnership, then deleted.",
      ],
    },
    {
      title: "8. Your Rights",
      paragraphs: ["Under UK GDPR, you have the right to:"],
      list: [
        "Ask us what personal data we hold about you and request a copy of it.",
        "Ask us to correct any inaccurate or incomplete data.",
        "Ask us to delete your data, where there is no legal reason for us to keep it.",
        "Ask us to restrict or object to how we use your data in certain circumstances, including being removed from our CRM at any time.",
        "Complain to the Information Commissioner's Office (ICO) if you believe we have not handled your data properly.",
      ],
      subsections: [
        {
          title: "",
          paragraphs: [
            `To exercise any of these rights, contact us at ${legalEmail}. We will respond within one month, as required by law.`,
            "The Information Commissioner's Office can be contacted at ico.org.uk or on 0303 123 1113 if you wish to raise a concern directly with the regulator.",
          ],
        },
      ],
    },
    {
      title: "9. Keeping Your Information Secure",
      paragraphs: [
        "We take reasonable technical and organisational steps to protect the personal data we hold, including restricting access to those who need it to do their job and using reputable, secure third-party tools (such as Calendly, Google Analytics, and Mailchimp) for the services described in this policy.",
      ],
    },
    {
      title: "10. Changes to This Policy",
      paragraphs: [
        "We may update this policy from time to time as our business and website evolve. The version in effect is dated at the top of this document. We encourage you to check this page periodically.",
      ],
    },
    {
      title: "11. Contact Us",
      paragraphs: [
        `If you have any questions about this policy or how we handle your personal data, please contact us at ${legalEmail}.`,
        "Plistic is the trading name of Songplistic Ltd, a company registered in Scotland under company number SC699049. Registered office: 2 West Drive Cottage, Stracathro, Brechin, Scotland, DD9 7QF.",
      ],
    },
  ],
};
